-- MySQL Script generated by MySQL Workbench
-- Sat Nov  5 19:09:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `user_id` TINYINT(1) NOT NULL,
  `user_name` VARCHAR(45) NULL,
  `user_address` VARCHAR(100) NULL,
  `user_street` VARCHAR(45) NULL,
  `user_zipcode` CHAR(5) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Member` (
  `member_id` TINYINT(1) NOT NULL,
  `member_name` VARCHAR(45) NOT NULL,
  `member_lastname` VARCHAR(45) NOT NULL,
  `member_address` VARCHAR(100) NULL,
  `member_state` VARCHAR(45) NULL,
  `member_zipcode` CHAR(5) NULL,
  `member_strees` VARCHAR(45) NULL,
  `member_dob` VARCHAR(45) NOT NULL,
  `member_year` VARCHAR(45) NOT NULL,
  `member_month` VARCHAR(45) NOT NULL,
  `member_day` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`member_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Account` (
  `account_id` TINYINT(1) NOT NULL,
  `account_username` VARCHAR(100) NOT NULL,
  `account_password` VARCHAR(100) NOT NULL,
  `Member_member_id` TINYINT(1) NOT NULL,
  PRIMARY KEY (`account_id`, `Member_member_id`),
  INDEX `fk_Account_Member1_idx` (`Member_member_id` ASC) VISIBLE,
  CONSTRAINT `fk_Account_Member1`
    FOREIGN KEY (`Member_member_id`)
    REFERENCES `mydb`.`Member` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventory` (
  `product_name` VARCHAR(45) NOT NULL,
  `product_price` DECIMAL(6,2) NOT NULL,
  `inventory_id` TINYINT(1) NOT NULL,
  `product_count` INT NOT NULL,
  PRIMARY KEY (`inventory_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `menu_id` TINYINT(1) NOT NULL,
  `product_price` DECIMAL(6,2) NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `Inventory_inventory_id` TINYINT(1) NOT NULL,
  PRIMARY KEY (`menu_id`),
  INDEX `fk_Menu_Inventory1_idx` (`Inventory_inventory_id` ASC) VISIBLE,
  CONSTRAINT `fk_Menu_Inventory1`
    FOREIGN KEY (`Inventory_inventory_id`)
    REFERENCES `mydb`.`Inventory` (`inventory_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CoffeeShop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CoffeeShop` (
  `shop_id` TINYINT(1) NOT NULL,
  `shop_name` VARCHAR(100) NOT NULL,
  `shop_address` VARCHAR(100) NOT NULL,
  `shop_street` VARCHAR(45) NOT NULL,
  `shop_zipcode` CHAR(5) NOT NULL,
  `shop_state` CHAR(2) NOT NULL,
  `Menu_menu_id` TINYINT(1) NOT NULL,
  PRIMARY KEY (`shop_id`, `Menu_menu_id`),
  INDEX `fk_CoffeeShop_Menu1_idx` (`Menu_menu_id` ASC) VISIBLE,
  CONSTRAINT `fk_CoffeeShop_Menu1`
    FOREIGN KEY (`Menu_menu_id`)
    REFERENCES `mydb`.`Menu` (`menu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `category_id` TINYINT(1) NOT NULL,
  `category_name` VARCHAR(45) NOT NULL,
  `category_description` VARCHAR(100) NULL,
  `Product_product_id` TINYINT(1) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brand` (
  `brand_id` TINYINT(1) NOT NULL,
  `brand_name` VARCHAR(100) NOT NULL,
  `supplier_name` VARCHAR(100) NOT NULL,
  `brand_supplier_id` TINYINT(1) NOT NULL,
  PRIMARY KEY (`brand_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `product_id` TINYINT(1) NOT NULL,
  `product_price` DECIMAL(6,2) NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `product_supplier_id` TINYINT(1) NOT NULL,
  `category_name` VARCHAR(45) NOT NULL,
  `Category_category_id1` TINYINT(1) NULL,
  `Brand_brand_id` TINYINT(1) NOT NULL,
  PRIMARY KEY (`product_id`, `Category_category_id1`),
  INDEX `fk_Product_Category1_idx` (`Category_category_id1` ASC) VISIBLE,
  INDEX `fk_Product_Brand1_idx` (`Brand_brand_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Category1`
    FOREIGN KEY (`Category_category_id1`)
    REFERENCES `mydb`.`Category` (`category_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Product_Brand1`
    FOREIGN KEY (`Brand_brand_id`)
    REFERENCES `mydb`.`Brand` (`brand_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `role_id` TINYINT(1) NOT NULL,
  `role_name` VARCHAR(45) NOT NULL,
  `role_description` VARCHAR(100) NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `employee_id` TINYINT(1) NOT NULL,
  `employee_name` VARCHAR(45) NOT NULL,
  `employee_lastname` VARCHAR(45) NOT NULL,
  `role_name` VARCHAR(45) NOT NULL,
  `Inventory_CoffeeShop_shop_id` TINYINT(1) NOT NULL,
  `CoffeeShop_shop_id` TINYINT(1) NOT NULL,
  `Role_role_id` TINYINT(1) NOT NULL,
  PRIMARY KEY (`employee_id`, `CoffeeShop_shop_id`, `Role_role_id`),
  INDEX `fk_Employee_CoffeeShop1_idx` (`CoffeeShop_shop_id` ASC) VISIBLE,
  INDEX `fk_Employee_Role1_idx` (`Role_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_CoffeeShop1`
    FOREIGN KEY (`CoffeeShop_shop_id`)
    REFERENCES `mydb`.`CoffeeShop` (`shop_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_Role1`
    FOREIGN KEY (`Role_role_id`)
    REFERENCES `mydb`.`Role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payment` (
  `payment_id` TINYINT(1) NOT NULL,
  `payment_type` VARCHAR(45) NOT NULL,
  `payment_ammount` DECIMAL(6,2) NULL,
  `Member_member_id` TINYINT(1) NOT NULL,
  `User_user_id` TINYINT(1) NOT NULL,
  PRIMARY KEY (`payment_id`, `Member_member_id`, `User_user_id`),
  INDEX `fk_Payment_Member1_idx` (`Member_member_id` ASC) VISIBLE,
  INDEX `fk_Payment_User1_idx` (`User_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Payment_Member1`
    FOREIGN KEY (`Member_member_id`)
    REFERENCES `mydb`.`Member` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Payment_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderStatus` (
  `orderstatus_code` INT NOT NULL,
  `orderstatus_description` VARCHAR(100) NULL,
  `orderstatus_timedaycompleted` DATETIME NULL,
  `orderstatus_id` TINYINT(1) NOT NULL,
  PRIMARY KEY (`orderstatus_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cart` (
  `cart_id` TINYINT(1) NOT NULL,
  `cart_total` DECIMAL(6,2) NOT NULL,
  `product_price` DECIMAL(6,2) NULL,
  `product_name` VARCHAR(45) NULL,
  `User_user_id` TINYINT(1) NOT NULL,
  `Product_product_id1` TINYINT(1) NULL,
  `Member_member_id` TINYINT(1) NOT NULL,
  PRIMARY KEY (`cart_id`, `User_user_id`, `Member_member_id`),
  INDEX `fk_Cart_User1_idx` (`User_user_id` ASC) VISIBLE,
  INDEX `fk_Cart_Product1_idx` (`Product_product_id1` ASC) VISIBLE,
  INDEX `fk_Cart_Member1_idx` (`Member_member_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cart_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cart_Product1`
    FOREIGN KEY (`Product_product_id1`)
    REFERENCES `mydb`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cart_Member1`
    FOREIGN KEY (`Member_member_id`)
    REFERENCES `mydb`.`Member` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu_has_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu_has_Product` (
  `Menu_menu_id` TINYINT(1) NULL,
  `Product_product_id` TINYINT(1) NOT NULL,
  `Product_Category_category_id1` TINYINT(1) NULL,
  PRIMARY KEY (`Menu_menu_id`, `Product_product_id`, `Product_Category_category_id1`),
  INDEX `fk_Menu_has_Product_Product1_idx` (`Product_product_id` ASC) VISIBLE,
  INDEX `fk_Menu_has_Product_Menu1_idx` (`Menu_menu_id` ASC) VISIBLE,
  INDEX `Product_category_category_id_idx` (`Product_Category_category_id1` ASC) VISIBLE,
  CONSTRAINT `fk_Menu_has_Product_Menu1`
    FOREIGN KEY (`Menu_menu_id`)
    REFERENCES `mydb`.`Menu` (`menu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Menu_has_Product_Product1`
    FOREIGN KEY (`Product_product_id`)
    REFERENCES `mydb`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Product_category_category_id`
    FOREIGN KEY (`Product_Category_category_id1`)
    REFERENCES `mydb`.`Category` (`category_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventory_has_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventory_has_Product` (
  `Inventory_CoffeeShop_shop_id` TINYINT(1) NOT NULL,
  `Product_product_id` TINYINT(1) NOT NULL,
  `Product_Category_category_id1` TINYINT(1) NULL,
  PRIMARY KEY (`Inventory_CoffeeShop_shop_id`, `Product_product_id`, `Product_Category_category_id1`),
  INDEX `fk_Inventory_has_Product_Product1_idx` (`Product_product_id` ASC) VISIBLE,
  INDEX `fk_Inventory_has_Product_product_category_idx` (`Product_Category_category_id1` ASC) VISIBLE,
  CONSTRAINT `fk_Inventory_has_Product_Product1`
    FOREIGN KEY (`Product_product_id`)
    REFERENCES `mydb`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Inventory_has_Product_category`
    FOREIGN KEY (`Product_Category_category_id1`)
    REFERENCES `mydb`.`Category` (`category_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `order_id` TINYINT(1) NOT NULL,
  `orderstatus_code` INT NOT NULL,
  `Cart_cart_id` TINYINT(1) NOT NULL,
  `Cart_User_user_id` TINYINT(1) NOT NULL,
  `OrderStatus_orderstatus_id` TINYINT(1) NOT NULL,
  PRIMARY KEY (`order_id`, `Cart_cart_id`, `Cart_User_user_id`, `OrderStatus_orderstatus_id`),
  INDEX `fk_Order_Cart1_idx` (`Cart_cart_id` ASC, `Cart_User_user_id` ASC) VISIBLE,
  INDEX `fk_Order_OrderStatus1_idx` (`OrderStatus_orderstatus_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Cart1`
    FOREIGN KEY (`Cart_cart_id` , `Cart_User_user_id`)
    REFERENCES `mydb`.`Cart` (`cart_id` , `User_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Order_OrderStatus1`
    FOREIGN KEY (`OrderStatus_orderstatus_id`)
    REFERENCES `mydb`.`OrderStatus` (`orderstatus_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `supplier_email` INT NOT NULL,
  `supplier_id` TINYINT(1) NOT NULL,
  `supplier_name` VARCHAR(45) NOT NULL,
  `supplier_address` VARCHAR(100) NOT NULL,
  `supplier_street` VARCHAR(45) NOT NULL,
  `supplier_zipcode` CHAR(45) NOT NULL,
  `supplier_state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`supplier_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_has_Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_has_Supplier` (
  `Product_product_id` TINYINT(1) NOT NULL,
  `Product_Category_category_id1` TINYINT(1) NULL,
  `Supplier_supplier_id` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Product_product_id`, `Product_Category_category_id1`, `Supplier_supplier_id`),
  INDEX `fk_Product_has_Supplier_Supplier1_idx` (`Supplier_supplier_id` ASC) VISIBLE,
  INDEX `fk_Product_has_Supplier_category_idx` (`Product_Category_category_id1` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Supplier_Product1`
    FOREIGN KEY (`Product_product_id`)
    REFERENCES `mydb`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Supplier_Supplier1`
    FOREIGN KEY (`Supplier_supplier_id`)
    REFERENCES `mydb`.`Supplier` (`supplier_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Product_has_Supplier_category`
    FOREIGN KEY (`Product_Category_category_id1`)
    REFERENCES `mydb`.`Category` (`category_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CoffeeShop_has_Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CoffeeShop_has_Supplier` (
  `CoffeeShop_shop_id` TINYINT(1) NOT NULL,
  `Supplier_supplier_id` TINYINT(1) NOT NULL,
  INDEX `fk_CoffeeShop_has_Supplier_Supplier1_idx` (`Supplier_supplier_id` ASC) VISIBLE,
  INDEX `fk_CoffeeShop_has_Supplier_CoffeeShop1_idx` (`CoffeeShop_shop_id` ASC) VISIBLE,
  CONSTRAINT `fk_CoffeeShop_has_Supplier_CoffeeShop1`
    FOREIGN KEY (`CoffeeShop_shop_id`)
    REFERENCES `mydb`.`CoffeeShop` (`shop_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CoffeeShop_has_Supplier_Supplier1`
    FOREIGN KEY (`Supplier_supplier_id`)
    REFERENCES `mydb`.`Supplier` (`supplier_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventory_has_Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventory_has_Supplier` (
  `Inventory_inventory_id` TINYINT(1) NOT NULL,
  `Supplier_supplier_id` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Inventory_inventory_id`, `Supplier_supplier_id`),
  INDEX `fk_Inventory_has_Supplier_Supplier1_idx` (`Supplier_supplier_id` ASC) VISIBLE,
  INDEX `fk_Inventory_has_Supplier_Inventory1_idx` (`Inventory_inventory_id` ASC) VISIBLE,
  CONSTRAINT `fk_Inventory_has_Supplier_Inventory1`
    FOREIGN KEY (`Inventory_inventory_id`)
    REFERENCES `mydb`.`Inventory` (`inventory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventory_has_Supplier_Supplier1`
    FOREIGN KEY (`Supplier_supplier_id`)
    REFERENCES `mydb`.`Supplier` (`supplier_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
